export const meals = [
  {
    id: 1,
    name: "Burger",
    price: 10,
    category: "Fast Food",
    image: "../images/meels/meel_1.jpg",
    description: "A juicy burger with lettuce, tomato, and cheese",
  },
  {
    id: 2,
    name: "Pizza",
    price: 15,
    category: "Italian",
    image: "../images/meels/meel_2.jpg",
    description: "A classic pizza with toppings of your choice",
  },
  {
    id: 3,
    name: "Sushi",
    price: 20,
    category: "Japanese",
    image: "../images/meels/meel_3.jpg",
    description: "A fresh and flavorful sushi roll with seaweed and rice",
  },
  {
    id: 4,
    name: "Pasta",
    price: 12,
    category: "Italian",
    image: "../images/meels/meel_4.jpg",
    description: "A classic pasta dish with tomato sauce and cheese",
  },
  {
    id: 5,
    name: "Steak",
    price: 25,
    category: "Grill",
    image: "../images/meels/meel_5.jpg",
    description: "A juicy steak with lettuce, tomato, and cheese",
  },
  {
    id: 6,
    name: "Salad",
    price: 8,
    category: "Fast Food",
    image: "../images/meels/meel_6.jpg",
    description: "A refreshing salad with mixed greens, tomatoes, and cheese",
  },
  {
    id: 7,
    name: "Tacos",
    price: 18,
    category: "Fast Food",
    image: "../images/meels/meel_7.jpg",
    description:
      "A delicious taco with a soft corn tortilla and a filling of your choice",
  },
  {
    id: 8,
    name: "Pancakes",
    price: 12,
    category: "Dessert",
    image: "../images/meels/meel_8.jpg",
    description: "A crispy pancake with maple syrup and a choice of toppings",
  },
  {
    id: 9,
    name: "Pizza",
    price: 15,
    category: "Italian",
    image: "../images/meels/meel_9.jpg",
    description: "A classic pizza with toppings of your choice",
  },
  {
    id: 10,
    name: "Sushi",
    price: 20,
    category: "Japanese",
    image: "../images/meels/meel_10.jpg",
    description: "A fresh and flavorful sushi roll with seaweed and rice",
  },
  {
    id: 11,
    name: "Pasta",
    price: 12,
    category: "Italian",
    image: "../images/meels/meel_11.jpg",
    description: "A classic pasta dish with tomato sauce and cheese",
  },
  {
    id: 12,
    name: "Steak",
    price: 25,
    category: "Grill",
    image: "../images/meels/meel_12.jpg",
    description: "A juicy steak with lettuce, tomato, and cheese",
  },
  {
    id: 13,
    name: "Salad",
    price: 8,
    category: "Fast Food",
    image: "../images/meels/meel_13.jpg",
    description: "A refreshing salad with mixed greens, tomatoes, and cheese",
  },
  {
    id: 14,
    name: "Tacos",
    price: 18,
    category: "Fast Food",
    image: "../images/meels/meel_14.jpg",
    description:
      "A delicious taco with a soft corn tortilla and a filling of your choice",
  },
  {
    id: 15,
    name: "Pancakes",
    price: 12,
    category: "Dessert",
    image: "../images/meels/meel_15.jpg",
    description: "A crispy pancake with maple syrup and a choice of toppings",
  },
];
